spring.application.name=LogisticUTEExpress

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/uteexpress?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JSP
# ===============================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ===============================
# MEDIA
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB
# ===============================
# JWT
# ===============================
app.jwt.secret=replace-this-with-a-long-random-secret-key-at-least-32-characters
app.jwt.expiration-ms=86400000
app.jwt.issuer=uteexpress